<?php if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true) die();?>
<?php
/**
 * @var \CMain $APPLICATION
 * @var PVP\Exchange\ExchangeComponent $exchangeComponent
 * @var CBitrixComponent $component pvp:exchange
 * @var array $arResult
 */
?>
<?php
global $arSetting;
$arSetting = $APPLICATION->IncludeComponent("altop:settings", "", array(), false, array("HIDE_ICONS" => "Y"));?>
<?php $elementID = $APPLICATION->IncludeComponent("bitrix:catalog.element", '',
    array(
        "IBLOCK_TYPE" => $exchangeComponent->getCatalogParam("IBLOCK_TYPE"),
        "IBLOCK_ID" => $exchangeComponent->getCatalogParam("IBLOCK_ID"),
        "PROPERTY_CODE" => $exchangeComponent->getCatalogParam("DETAIL_PROPERTY_CODE"),
        "META_KEYWORDS" => $exchangeComponent->getCatalogParam("DETAIL_META_KEYWORDS"),
        "META_DESCRIPTION" => $exchangeComponent->getCatalogParam("DETAIL_META_DESCRIPTION"),
        "BROWSER_TITLE" => $exchangeComponent->getCatalogParam("DETAIL_BROWSER_TITLE"),
        "SET_CANONICAL_URL" => $exchangeComponent->getCatalogParam("DETAIL_SET_CANONICAL_URL"),
        "BASKET_URL" => $exchangeComponent->getCatalogParam("BASKET_URL"),
        "ACTION_VARIABLE" => $exchangeComponent->getCatalogParam("ACTION_VARIABLE"),
        "PRODUCT_ID_VARIABLE" => $exchangeComponent->getCatalogParam("PRODUCT_ID_VARIABLE"),
        "SECTION_ID_VARIABLE" => $exchangeComponent->getCatalogParam("SECTION_ID_VARIABLE"),
        "CHECK_SECTION_ID_VARIABLE" => ($exchangeComponent->getCatalogParam("DETAIL_CHECK_SECTION_ID_VARIABLE") ? : ""),
        "PRODUCT_QUANTITY_VARIABLE" => $exchangeComponent->getCatalogParam("PRODUCT_QUANTITY_VARIABLE"),
        "PRODUCT_PROPS_VARIABLE" => $exchangeComponent->getCatalogParam("PRODUCT_PROPS_VARIABLE"),
        "CACHE_TYPE" => $exchangeComponent->getCatalogParam("CACHE_TYPE"),
        "CACHE_TIME" => $exchangeComponent->getCatalogParam("CACHE_TIME"),
        "CACHE_GROUPS" => $exchangeComponent->getCatalogParam("CACHE_GROUPS"),
        "SET_TITLE" => $exchangeComponent->getCatalogParam("SET_TITLE"),
        "SET_LAST_MODIFIED" => $exchangeComponent->getCatalogParam("SET_LAST_MODIFIED"),
        "MESSAGE_404" => $exchangeComponent->getCatalogParam("MESSAGE_404"),
        "SET_STATUS_404" => $exchangeComponent->getCatalogParam("SET_STATUS_404"),
        "SHOW_404" => $exchangeComponent->getCatalogParam("SHOW_404"),
        "FILE_404" => $exchangeComponent->getCatalogParam("FILE_404"),
        "PRICE_CODE" => $exchangeComponent->getCatalogParam("PRICE_CODE"),
        "USE_PRICE_COUNT" => $exchangeComponent->getCatalogParam("USE_PRICE_COUNT"),
        "SHOW_PRICE_COUNT" => $exchangeComponent->getCatalogParam("SHOW_PRICE_COUNT"),
        "PRICE_VAT_INCLUDE" => $exchangeComponent->getCatalogParam("PRICE_VAT_INCLUDE"),
        "PRICE_VAT_SHOW_VALUE" => $exchangeComponent->getCatalogParam("PRICE_VAT_SHOW_VALUE"),
        "USE_PRODUCT_QUANTITY" => $exchangeComponent->getCatalogParam("USE_PRODUCT_QUANTITY"),
        "PRODUCT_PROPERTIES" => $exchangeComponent->getCatalogParam("PRODUCT_PROPERTIES"),
        "ADD_PROPERTIES_TO_BASKET" => ($exchangeComponent->getCatalogParam("ADD_PROPERTIES_TO_BASKET") ? : ""),
        "PARTIAL_PRODUCT_PROPERTIES" => ($exchangeComponent->getCatalogParam("PARTIAL_PRODUCT_PROPERTIES") ? : ""),
        "LINK_IBLOCK_TYPE" => $exchangeComponent->getCatalogParam("LINK_IBLOCK_TYPE"),
        "LINK_IBLOCK_ID" => $exchangeComponent->getCatalogParam("LINK_IBLOCK_ID"),
        "LINK_PROPERTY_SID" => $exchangeComponent->getCatalogParam("LINK_PROPERTY_SID"),
        "LINK_ELEMENTS_URL" => $exchangeComponent->getCatalogParam("LINK_ELEMENTS_URL"),
        "OFFERS_CART_PROPERTIES" => $exchangeComponent->getCatalogParam("OFFERS_CART_PROPERTIES"),
        "OFFERS_FIELD_CODE" => $exchangeComponent->getCatalogParam("DETAIL_OFFERS_FIELD_CODE"),
        "OFFERS_PROPERTY_CODE" => $exchangeComponent->getCatalogParam("DETAIL_OFFERS_PROPERTY_CODE"),
        "OFFERS_SORT_FIELD" => $exchangeComponent->getCatalogParam("OFFERS_SORT_FIELD_EL"),
        "OFFERS_SORT_ORDER" => $exchangeComponent->getCatalogParam("OFFERS_SORT_ORDER"),
        "OFFERS_SORT_FIELD2" => $exchangeComponent->getCatalogParam("OFFERS_SORT_FIELD2"),
        "OFFERS_SORT_ORDER2" => $exchangeComponent->getCatalogParam("OFFERS_SORT_ORDER2"),
        "OFFERS_SORT_FIELD3" => $exchangeComponent->getCatalogParam("OFFERS_SORT_FIELD3"),
        //CURRENT ELEMENT PARAMS
        "ELEMENT_ID" => $arResult['ELEMENT_ID'],
        "SECTION_CODE" => $arResult['SECTION_CODE'],
//        "ELEMENT_CODE" => 'terka_ppu_8kh26_1',
//        "SECTION_ID" => 0,
//        "SECTION_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["section"],
//        "DETAIL_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["element"],
        /*--------------------------------------------------------------------------*/
        "CONVERT_CURRENCY" => $exchangeComponent->getCatalogParam("CONVERT_CURRENCY"),
        "CURRENCY_ID" => $exchangeComponent->getCatalogParam("CURRENCY_ID"),
        "HIDE_NOT_AVAILABLE" => $exchangeComponent->getCatalogParam("HIDE_NOT_AVAILABLE"),
        "HIDE_NOT_AVAILABLE_OFFERS" => $exchangeComponent->getCatalogParam("HIDE_NOT_AVAILABLE_OFFERS"),
        "USE_ELEMENT_COUNTER" => $exchangeComponent->getCatalogParam("USE_ELEMENT_COUNTER"),
        "SHOW_DEACTIVATED" => $exchangeComponent->getCatalogParam("SHOW_DEACTIVATED"),
        "USE_MAIN_ELEMENT_SECTION" => $exchangeComponent->getCatalogParam("USE_MAIN_ELEMENT_SECTION"),
        "MAIN_BLOCK_PROPERTY_CODE" => $exchangeComponent->getCatalogParam("DETAIL_MAIN_BLOCK_PROPERTY_CODE"),
        "MAIN_BLOCK_OFFERS_PROPERTY_CODE" => $exchangeComponent->getCatalogParam("DETAIL_MAIN_BLOCK_OFFERS_PROPERTY_CODE"),
        "ADD_SECTIONS_CHAIN" => ($exchangeComponent->getCatalogParam("ADD_SECTIONS_CHAIN") ? : ""),
        "ADD_ELEMENT_CHAIN" => ($exchangeComponent->getCatalogParam("ADD_ELEMENT_CHAIN") ? : ""),
        "DISPLAY_COMPARE" => ($exchangeComponent->getCatalogParam("USE_COMPARE") ? : ""),
        //"COMPARE_PATH" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["compare"], //NOT USE
        "BACKGROUND_IMAGE" => ($exchangeComponent->getCatalogParam("DETAIL_BACKGROUND_IMAGE") ? : ""),
        "DISABLE_INIT_JS_IN_COMPONENT" => ($exchangeComponent->getCatalogParam("DISABLE_INIT_JS_IN_COMPONENT") ? : ""),
        "SET_VIEWED_IN_COMPONENT" => ($exchangeComponent->getCatalogParam("DETAIL_SET_VIEWED_IN_COMPONENT") ? : ""),
        "SHOW_MAX_QUANTITY" => $exchangeComponent->getCatalogParam("SHOW_MAX_QUANTITY"),
        "MESS_SHOW_MAX_QUANTITY" => ($exchangeComponent->getCatalogParam("~MESS_SHOW_MAX_QUANTITY") ? : ""),
        "RELATIVE_QUANTITY_FACTOR" => ($exchangeComponent->getCatalogParam("RELATIVE_QUANTITY_FACTOR") ? : ""),
        "MESS_RELATIVE_QUANTITY_MANY" => ($exchangeComponent->getCatalogParam("~MESS_RELATIVE_QUANTITY_MANY") ? : ""),
        "MESS_RELATIVE_QUANTITY_FEW" => ($exchangeComponent->getCatalogParam("~MESS_RELATIVE_QUANTITY_FEW") ? : ""),
        "USE_STORE" => $exchangeComponent->getCatalogParam("USE_STORE"),
        "STORE_PATH" => $exchangeComponent->getCatalogParam('STORE_PATH'),
        "MAIN_TITLE" => $exchangeComponent->getCatalogParam('MAIN_TITLE'),
        "USE_MIN_AMOUNT" => $exchangeComponent->getCatalogParam('USE_MIN_AMOUNT'),
        "MIN_AMOUNT" => $exchangeComponent->getCatalogParam('MIN_AMOUNT'),
        "STORES" => $exchangeComponent->getCatalogParam('STORES'),
        "SHOW_EMPTY_STORE" => $exchangeComponent->getCatalogParam('SHOW_EMPTY_STORE'),
        "SHOW_GENERAL_STORE_INFORMATION" => $exchangeComponent->getCatalogParam('SHOW_GENERAL_STORE_INFORMATION'),
        "USER_FIELDS" => $exchangeComponent->getCatalogParam('USER_FIELDS'),
        "FIELDS" => $exchangeComponent->getCatalogParam('FIELDS'),
        "DISPLAY_IMG_WIDTH"	 =>	$exchangeComponent->getCatalogParam("DISPLAY_IMG_WIDTH"),
        "DISPLAY_IMG_HEIGHT" =>	$exchangeComponent->getCatalogParam("DISPLAY_IMG_HEIGHT"),
        "DISPLAY_DETAIL_IMG_WIDTH"	 =>	$exchangeComponent->getCatalogParam("DISPLAY_DETAIL_IMG_WIDTH"),
        "DISPLAY_DETAIL_IMG_HEIGHT" =>	$exchangeComponent->getCatalogParam("DISPLAY_DETAIL_IMG_HEIGHT"),
        "DISPLAY_MORE_PHOTO_WIDTH"	 =>	$exchangeComponent->getCatalogParam("DISPLAY_MORE_PHOTO_WIDTH"),
        "DISPLAY_MORE_PHOTO_HEIGHT" =>	$exchangeComponent->getCatalogParam("DISPLAY_MORE_PHOTO_HEIGHT"),
        "PROPERTY_CODE_MOD" => $exchangeComponent->getCatalogParam("PROPERTY_CODE_MOD"),
        "IBLOCK_TYPE_REVIEWS" => $exchangeComponent->getCatalogParam("IBLOCK_TYPE_REVIEWS"),
        "IBLOCK_ID_REVIEWS" => $exchangeComponent->getCatalogParam("IBLOCK_ID_REVIEWS"),
        "BUTTON_PAYMENTS_HREF" => $exchangeComponent->getCatalogParam("BUTTON_PAYMENTS_HREF"),
        "BUTTON_CREDIT_HREF" => $exchangeComponent->getCatalogParam("BUTTON_CREDIT_HREF"),
        "BUTTON_DELIVERY_HREF" => $exchangeComponent->getCatalogParam("BUTTON_DELIVERY_HREF"),
        "AJAX_OPTION_HISTORY" => $exchangeComponent->getCatalogParam("AJAX_OPTION_HISTORY"),
        "AJAX_MODE" => $exchangeComponent->getCatalogParam("AJAX_MODE"),
        "STRICT_SECTION_CHECK" => $exchangeComponent->getCatalogParam("DETAIL_STRICT_SECTION_CHECK"),
        "USE_GIFTS_DETAIL" => $exchangeComponent->getCatalogParam("USE_GIFTS_DETAIL"),
        "GIFTS_DETAIL_HIDE_BLOCK_TITLE" => $exchangeComponent->getCatalogParam("GIFTS_DETAIL_HIDE_BLOCK_TITLE"),
        "GIFTS_DETAIL_BLOCK_TITLE" => $exchangeComponent->getCatalogParam("GIFTS_DETAIL_BLOCK_TITLE"),
        "1CB_USE_FILE_FIELD" => $exchangeComponent->getCatalogParam("1CB_USE_FILE_FIELD"),
        "1CB_FILE_FIELD_MULTIPLE" => $exchangeComponent->getCatalogParam("1CB_FILE_FIELD_MULTIPLE"),
        "1CB_FILE_FIELD_MAX_COUNT" => $exchangeComponent->getCatalogParam("1CB_FILE_FIELD_MAX_COUNT"),
        "1CB_FILE_FIELD_NAME" => $exchangeComponent->getCatalogParam("1CB_FILE_FIELD_NAME"),
        "1CB_FILE_FIELD_TYPE" => $exchangeComponent->getCatalogParam("1CB_FILE_FIELD_TYPE"),
        "1CB_REQUIRED_FIELDS" => $exchangeComponent->getCatalogParam("1CB_REQUIRED_FIELDS"),
        "NUMBER_ACCESSORIES" => $exchangeComponent->getCatalogParam("NUMBER_ACCESSORIES"),
        "COUNT_REVIEW" => $exchangeComponent->getCatalogParam("COUNT_REVIEW")
    ),
    $component
);?>
<?php
if (! $elementID) {
    \PVP\Exchange\ErrorManager::getInstance()->addError('Элемент недоступен');
}

