<?php if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true) die();?>
<?php
/**
 * @var \CMain $APPLICATION
 * @var PVP\Exchange\ExchangeComponent $exchangeComponent
 * @var CBitrixComponent $component pvp:exchange
 */
?>
<?php
$APPLICATION->IncludeComponent("bitrix:catalog.search", "",
    array(
        "IBLOCK_TYPE" => $exchangeComponent->getCatalogParam("IBLOCK_TYPE"),
        "IBLOCK_ID" => $exchangeComponent->getCatalogParam("IBLOCK_ID"),
        "ELEMENT_SORT_FIELD" => $exchangeComponent->getCatalogParam("ELEMENT_SORT_FIELD"),
        "ELEMENT_SORT_ORDER" => $exchangeComponent->getCatalogParam("ELEMENT_SORT_ORDER"),
        "ELEMENT_SORT_FIELD2" => $exchangeComponent->getCatalogParam("ELEMENT_SORT_FIELD2"),
        "ELEMENT_SORT_ORDER2" => $exchangeComponent->getCatalogParam("ELEMENT_SORT_ORDER2"),
        "PAGE_ELEMENT_COUNT" => $exchangeComponent->getCatalogParam("PAGE_ELEMENT_COUNT"),
        "LINE_ELEMENT_COUNT" => $exchangeComponent->getCatalogParam("LINE_ELEMENT_COUNT"),
        "PROPERTY_CODE" => $exchangeComponent->getCatalogParam("LIST_PROPERTY_CODE"),
        "OFFERS_CART_PROPERTIES" => $exchangeComponent->getCatalogParam("OFFERS_CART_PROPERTIES"),
        "OFFERS_FIELD_CODE" => $exchangeComponent->getCatalogParam("LIST_OFFERS_FIELD_CODE"),
        "OFFERS_PROPERTY_CODE" => $exchangeComponent->getCatalogParam("LIST_OFFERS_PROPERTY_CODE"),
        "OFFERS_SORT_FIELD" => $exchangeComponent->getCatalogParam("OFFERS_SORT_FIELD"),
        "OFFERS_SORT_ORDER" => $exchangeComponent->getCatalogParam("OFFERS_SORT_ORDER"),
        "OFFERS_SORT_FIELD2" => $exchangeComponent->getCatalogParam("OFFERS_SORT_FIELD2"),
        "OFFERS_SORT_ORDER2" => $exchangeComponent->getCatalogParam("OFFERS_SORT_ORDER2"),
        "OFFERS_LIMIT" => $exchangeComponent->getCatalogParam("OFFERS_LIMIT"),
        "SECTION_URL" => $exchangeComponent->getCatalogParam("SECTION_URL"),
        "DETAIL_URL" => $exchangeComponent->getCatalogParam("DETAIL_URL"),
        "BASKET_URL" => $exchangeComponent->getCatalogParam("BASKET_URL"),
        "ACTION_VARIABLE" => $exchangeComponent->getCatalogParam("ACTION_VARIABLE") ? $exchangeComponent->getCatalogParam("ACTION_VARIABLE") : "action",
        "PRODUCT_ID_VARIABLE" => $exchangeComponent->getCatalogParam("PRODUCT_ID_VARIABLE"),
        "PRODUCT_QUANTITY_VARIABLE" => $exchangeComponent->getCatalogParam("PRODUCT_QUANTITY_VARIABLE"),
        "PRODUCT_PROPS_VARIABLE" => $exchangeComponent->getCatalogParam("PRODUCT_PROPS_VARIABLE"),
        "SECTION_ID_VARIABLE" => $exchangeComponent->getCatalogParam("SECTION_ID_VARIABLE"),
        "CACHE_TYPE" => $exchangeComponent->getCatalogParam("CACHE_TYPE"),
        "CACHE_TIME" => $exchangeComponent->getCatalogParam("CACHE_TIME"),
        "DISPLAY_COMPARE" => $exchangeComponent->getCatalogParam("USE_COMPARE"),
        "PRICE_CODE" => $exchangeComponent->getCatalogParam("PRICE_CODE"),
        "USE_PRICE_COUNT" => $exchangeComponent->getCatalogParam("USE_PRICE_COUNT"),
        "SHOW_PRICE_COUNT" => $exchangeComponent->getCatalogParam("SHOW_PRICE_COUNT"),
        "PRICE_VAT_INCLUDE" => $exchangeComponent->getCatalogParam("PRICE_VAT_INCLUDE"),
        "ADD_PROPERTIES_TO_BASKET" => $exchangeComponent->getCatalogParam("ADD_PROPERTIES_TO_BASKET") ? $exchangeComponent->getCatalogParam("ADD_PROPERTIES_TO_BASKET") : "",
        "PARTIAL_PRODUCT_PROPERTIES" => $exchangeComponent->getCatalogParam("PARTIAL_PRODUCT_PROPERTIES") ? $exchangeComponent->getCatalogParam("PARTIAL_PRODUCT_PROPERTIES") : "",
        "PRODUCT_PROPERTIES" => $exchangeComponent->getCatalogParam("PRODUCT_PROPERTIES"),
        "USE_PRODUCT_QUANTITY" => $exchangeComponent->getCatalogParam("USE_PRODUCT_QUANTITY"),
        "CONVERT_CURRENCY" => $exchangeComponent->getCatalogParam("CONVERT_CURRENCY"),
        "CURRENCY_ID" => $exchangeComponent->getCatalogParam("CURRENCY_ID"),
        "HIDE_NOT_AVAILABLE" => $exchangeComponent->getCatalogParam("HIDE_NOT_AVAILABLE"),
        "HIDE_NOT_AVAILABLE_OFFERS" => $exchangeComponent->getCatalogParam("HIDE_NOT_AVAILABLE_OFFERS") ? $exchangeComponent->getCatalogParam("HIDE_NOT_AVAILABLE_OFFERS") : "",
        "DISPLAY_TOP_PAGER" => $exchangeComponent->getCatalogParam("DISPLAY_TOP_PAGER"),
        "DISPLAY_BOTTOM_PAGER" => $exchangeComponent->getCatalogParam("DISPLAY_BOTTOM_PAGER"),
        "PAGER_TITLE" => $exchangeComponent->getCatalogParam("PAGER_TITLE"),
        "PAGER_SHOW_ALWAYS" => $exchangeComponent->getCatalogParam("PAGER_SHOW_ALWAYS"),
        "PAGER_TEMPLATE" => $exchangeComponent->getCatalogParam("PAGER_TEMPLATE"),
        "PAGER_DESC_NUMBERING" => $exchangeComponent->getCatalogParam("PAGER_DESC_NUMBERING"),
        "PAGER_DESC_NUMBERING_CACHE_TIME" => $exchangeComponent->getCatalogParam("PAGER_DESC_NUMBERING_CACHE_TIME"),
        "PAGER_SHOW_ALL" => $exchangeComponent->getCatalogParam("PAGER_SHOW_ALL"),
        "LAZY_LOAD" => $exchangeComponent->getCatalogParam("LAZY_LOAD") ? $exchangeComponent->getCatalogParam("LAZY_LOAD") : "",
        "MESS_BTN_LAZY_LOAD" => $exchangeComponent->getCatalogParam("~MESS_BTN_LAZY_LOAD") ? $exchangeComponent->getCatalogParam("~MESS_BTN_LAZY_LOAD") : "",
        "LOAD_ON_SCROLL" => $exchangeComponent->getCatalogParam("LOAD_ON_SCROLL") ? $exchangeComponent->getCatalogParam("LOAD_ON_SCROLL") : "",
        "FILTER_NAME" => "searchFilter",
        "SECTION_ID" => "",
        "SECTION_CODE" => "",
        "SECTION_USER_FIELDS" => array(),
        "INCLUDE_SUBSECTIONS" => "Y",
        "SHOW_ALL_WO_SECTION" => "Y",
        "META_KEYWORDS" => "",
        "META_DESCRIPTION" => "",
        "BROWSER_TITLE" => "",
        "ADD_SECTIONS_CHAIN" => "N",
        "SET_TITLE" => "N",
        "SET_STATUS_404" => "N",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "N",
        "COMPARE_PATH" => $exchangeComponent->getCatalogParam("COMPARE_PATH"),
        "PAGE_RESULT_COUNT" => $exchangeComponent->getCatalogParam("SEARCH_PAGE_RESULT_COUNT") ? $exchangeComponent->getCatalogParam("SEARCH_PAGE_RESULT_COUNT") : "300",
        "RESTART" => $exchangeComponent->getCatalogParam("SEARCH_RESTART") ? $exchangeComponent->getCatalogParam("SEARCH_RESTART") : "N",
        "NO_WORD_LOGIC" => $exchangeComponent->getCatalogParam("SEARCH_NO_WORD_LOGIC") ? $exchangeComponent->getCatalogParam("SEARCH_NO_WORD_LOGIC") : "Y",
        "USE_LANGUAGE_GUESS" => $exchangeComponent->getCatalogParam("SEARCH_USE_LANGUAGE_GUESS") ?$exchangeComponent->getCatalogParam("SEARCH_USE_LANGUAGE_GUESS") : "Y",
        "CHECK_DATES" => $exchangeComponent->getCatalogParam("SEARCH_CHECK_DATES") ? $exchangeComponent->getCatalogParam("SEARCH_CHECK_DATES") : "Y",
        "PRODUCT_ROW_VARIANTS" => $exchangeComponent->getCatalogParam("LIST_PRODUCT_ROW_VARIANTS") ? $exchangeComponent->getCatalogParam("LIST_PRODUCT_ROW_VARIANTS") : "",
        "DISPLAY_IMG_WIDTH"	 =>	$exchangeComponent->getCatalogParam("DISPLAY_IMG_WIDTH"),
        "DISPLAY_IMG_HEIGHT" =>	$exchangeComponent->getCatalogParam("DISPLAY_IMG_HEIGHT"),
        "PROPERTY_CODE_MOD" => $exchangeComponent->getCatalogParam("PROPERTY_CODE_MOD"),
        "SHOW_MAX_QUANTITY" => $exchangeComponent->getCatalogParam("SHOW_MAX_QUANTITY"),
        "MESS_SHOW_MAX_QUANTITY" => $exchangeComponent->getCatalogParam("~MESS_SHOW_MAX_QUANTITY") ? $exchangeComponent->getCatalogParam("~MESS_SHOW_MAX_QUANTITY") : "",
        "RELATIVE_QUANTITY_FACTOR" => $exchangeComponent->getCatalogParam("RELATIVE_QUANTITY_FACTOR") ? $exchangeComponent->getCatalogParam("RELATIVE_QUANTITY_FACTOR") : "",
        "MESS_RELATIVE_QUANTITY_MANY" => $exchangeComponent->getCatalogParam("~MESS_RELATIVE_QUANTITY_MANY") ? $exchangeComponent->getCatalogParam("~MESS_RELATIVE_QUANTITY_MANY") : "",
        "MESS_RELATIVE_QUANTITY_FEW" => $exchangeComponent->getCatalogParam("~MESS_RELATIVE_QUANTITY_FEW") ? $exchangeComponent->getCatalogParam("~MESS_RELATIVE_QUANTITY_FEW") : "",
        "BUTTON_PAYMENTS_HREF" => $exchangeComponent->getCatalogParam("BUTTON_PAYMENTS_HREF"),
        "BUTTON_CREDIT_HREF" => $exchangeComponent->getCatalogParam("BUTTON_CREDIT_HREF"),
        "BUTTON_DELIVERY_HREF" => $exchangeComponent->getCatalogParam("BUTTON_DELIVERY_HREF"),

    ),
    $component,
    array("HIDE_ICONS" => "Y")
);?>